### PR TITLE
chore(#25): Update README with local testing flow

### PR DESCRIPTION
**Pull request by Phil-Mwago**
# Description

Update README with local testing flow

[medic/interoperability#25](https://github.com/medic/interoperability/issues/25)

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by andrablaj** [comment]
@Phil-Mwago I will add some clarification directly in a commit. This is an exception, as we are on a tight timeline to merge this.

**Comment by andrablaj** [comment]
@Phil-Mwago I changed the style to make the text more readable and added screenshots.
As a tip, I usually use [this CheatSheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to ensure to see the style options; I never remember them by heart. 😅

**Review by andrablaj — APPROVED** [review]
Thanks @Phil-Mwago! I think this is ready to be merged. We can always update it later if something doesn't seem clear or if we have extra steps to add.

**Comment by Phil-Mwago** [comment]
Thanks @andrablaj this is well noted and thanks for the tip.

**Pull request merged**
